#spring.profiles.active: local
server:
  port: 8092
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    con.github.johnlayton: DEBUG

cxf:
  path: /service