#spring.profiles.active: local
server:
  port: 8092
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    con.github.johnlayton: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8093

cxf:
  path: /service